name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # or the branch you want to trigger the deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Authenticate with Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 3: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'beta'

      # Step 4: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud run deploy hello-cloudrun \
            --source . \
            --region asia-south1 \
            --platform managed \
            --allow-unauthenticated
