name: GCP Cloud Run Deployment

on:
  push:
    branches:
      - main  # Or any other branch you want to trigger the deployment from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: shashigcp-454502  # Replace with your GCP project ID
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}  # Path to the secret containing the GCP service account credentials

      # Step 3: Authenticate using the service account credentials
      - name: Authenticate to Google Cloud
        run: |
          gcloud auth activate-service-account --key-file="${{ secrets.GCP_CREDENTIALS }}"

      # Step 4: Set GCloud project
      - name: Set GCloud project
        run: |
          gcloud config set project shashigcp-454502  # Replace with your GCP project ID

      # Step 5: Build and deploy the container to Cloud Run
      - name: Build and deploy to Cloud Run
        run: |
          gcloud run deploy hello-cloudrun \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/hello-cloudrun \
            --platform managed \
            --region asia-south1 \
            --allow-unauthenticated  # Set this to 'false' if you want to restrict access
